// Generated by CoffeeScript 1.7.1
(function() {
  var ElasticScroll, Q, qhttp, url;

  Q = require('q');

  qhttp = require('q-io/http');

  url = require('url');

  ElasticScroll = (function() {
    function ElasticScroll(url, query, process_fn) {
      this.url = url;
      this.query = query;
      this.process_fn = process_fn;
      this.scroll_id = null;
    }

    ElasticScroll.prototype.set_scroll_id = function() {
      var request;
      request = {
        method: "POST",
        body: [JSON.stringify(this.query)],
        url: "" + this.url + "/_search?search_type=scan&scroll=10m&size=100"
      };
      return qhttp.request(request).then(function(response) {
        return response.body.read();
      }).then(function(resp) {
        return JSON.parse(resp.toString());
      }).then((function(_this) {
        return function(json) {
          console.error("TOTAL:", json.hits.total);
          return _this.scroll_id = json._scroll_id;
        };
      })(this));
    };

    ElasticScroll.prototype.get_next_set = function() {
      var host_name, parsed_url, request;
      process.stderr.write(".");
      parsed_url = url.parse(this.url);
      host_name = "" + parsed_url.protocol + "//" + parsed_url.host;
      request = {
        method: "GET",
        url: "" + host_name + "/_search/scroll/" + this.scroll_id + "?scroll=10m"
      };
      return qhttp.request(request).then(function(response) {
        return response.body.read();
      }).then(function(resp) {
        return JSON.parse(resp.toString());
      }).then(function(json) {
        return json.hits.hits;
      });
    };

    ElasticScroll.prototype.process_hits = function(hits) {
      var hit, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = hits.length; _i < _len; _i++) {
        hit = hits[_i];
        _results.push(this.process_fn(hit));
      }
      return _results;
    };

    ElasticScroll.prototype.continue_scroll = function(hits) {
      if (hits.length === 0) {
        return;
      }
      return this.get_next_set().then((function(_this) {
        return function(hits) {
          return _this.process_hits(hits);
        };
      })(this)).then((function(_this) {
        return function(hits) {
          return _this.continue_scroll(hits);
        };
      })(this));
    };

    ElasticScroll.prototype.scroll = function() {
      return Q.fcall(function() {
        return console.error("STARTING");
      }).then((function(_this) {
        return function() {
          return _this.set_scroll_id(_this.query);
        };
      })(this)).then((function(_this) {
        return function() {
          return _this.get_next_set();
        };
      })(this)).then((function(_this) {
        return function(hits) {
          return _this.process_hits(hits);
        };
      })(this)).then((function(_this) {
        return function(hits) {
          return _this.continue_scroll(hits);
        };
      })(this));
    };

    return ElasticScroll;

  })();

  if (typeof define !== 'undefined' && define.amd) {
    define([], function() {
      return ElasticScroll;
    });
  } else if (typeof module !== 'undefined' && module.exports) {
    module.exports = ElasticScroll;
  }

}).call(this);
